# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Linux Releases (x64 and Arm64)

on:
  push:
    tags:
      - 'v*'  # This will match any tag that starts with 'v'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (x64)
      run: dotnet publish -c Release -r linux-x64 -p:DebugType=none --self-contained true
    - name: Make Release Folder
      run: mkdir ./release/
    - name: Copy Binary (x64)
      run: |
        set -e
        cp ./bin/Release/net9.0/linux-x64/publish/BatteryStatus ./BatteryStatus
    - name: Zip Release (x64)
      run: zip -r "./release/BatteryStatus-${GITHUB_REF##*/}-linux-x64.zip" ./BatteryStatus ./batterystatus.service ./Icons
    - name: Build (arm64)
      run: dotnet publish -c Release -r linux-arm64 -p:DebugType=none --self-contained true
    - name: Copy Binary (arm64)
      run: |
        set -e
        rm ./BatteryStatus #remove the previous binary (from x64)
        cp ./bin/Release/net9.0/linux-arm64/publish/BatteryStatus ./BatteryStatus
    - name: Zip Release (arm64)
      run: zip -r "./release/BatteryStatus-${GITHUB_REF##*/}-linux-arm64.zip" ./BatteryStatus ./batterystatus.service ./Icons
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: ./release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
